"""optional message

Revision ID: a96f7cf65e85
Revises: 
Create Date: 2020-01-16 12:33:29.698093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96f7cf65e85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_name', sa.Text(), nullable=True),
    sa.Column('Student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Student_id'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('Student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Student_id'], ['Student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentor')
    op.drop_table('Subjects')
    op.drop_table('Student')
    # ### end Alembic commands ###
